loadstring(
    game:HttpGet(
        "https://raw.githubusercontent.com/Introvert1337/RobloxReleases/main/Scripts/RoBeats/AccuracyHelper.lua"
    )
)()
wait(0.1)
loadstring(
    game:HttpGet("https://raw.githubusercontent.com/Introvert1337/RobloxReleases/main/Scripts/RoBeats/Autoplayer.lua")
)()
wait(0.1)
print("executed")
